#!/bin/bash

# 7Zip Max Compression Script
# By Jesse N. Richardson (Flare183, negativeflare) [flare183@charter.net]

# Reference:
# 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on archive.7z dir1


echo "Usage 7zip.sh <archive name.7z> <directory>"
7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on "$1" "$2"
