#!/bin/bash

# Weather Script
# Written by Jesse N. Richardson (Flare183, negativeflare) [flare183@charter.net]

# Filename: weather

#watch -c -n 300 curl wttr.in/sawmills

while true
do
    clear
    echo "    "
    echo "    "
    echo "    "
    echo "    "
    echo "    "
    echo "    "
    date -R
    curl wttr.in/seneca_us
    sleep 1200
done
